
# cargo-vet config file

[cargo-vet]
version = "0.10"

[imports.OpenDevicePartnership]
url = "https://raw.githubusercontent.com/OpenDevicePartnership/rust-crate-audits/main/audits.toml"

[imports.actix]
url = "https://raw.githubusercontent.com/actix/supply-chain/main/audits.toml"

[imports.bytecode-alliance]
url = "https://raw.githubusercontent.com/bytecodealliance/wasmtime/main/supply-chain/audits.toml"

[imports.embark-studios]
url = "https://raw.githubusercontent.com/EmbarkStudios/rust-ecosystem/main/audits.toml"

[imports.fermyon]
url = "https://raw.githubusercontent.com/fermyon/spin/main/supply-chain/audits.toml"

[imports.google]
url = "https://raw.githubusercontent.com/google/rust-crate-audits/main/audits.toml"

[imports.isrg]
url = "https://raw.githubusercontent.com/divviup/libprio-rs/main/supply-chain/audits.toml"

[imports.mozilla]
url = "https://raw.githubusercontent.com/mozilla/supply-chain/main/audits.toml"

[imports.zcash]
url = "https://raw.githubusercontent.com/zcash/rust-ecosystem/main/supply-chain/audits.toml"

[policy.embassy-embedded-hal]
audit-as-crates-io = false

[policy.embassy-executor]
audit-as-crates-io = false

[policy.embassy-executor-macros]
audit-as-crates-io = false

[policy.embassy-futures]
audit-as-crates-io = false

[policy.embassy-hal-internal]
audit-as-crates-io = false

[policy.embassy-imxrt]
audit-as-crates-io = false

[policy.embassy-sync]
audit-as-crates-io = false

[policy.embassy-time]
audit-as-crates-io = false

[policy.embassy-time-driver]
audit-as-crates-io = false

[policy.embassy-time-queue-utils]
audit-as-crates-io = false
